package attendance;
// Generated Dec 18, 2014 9:57:35 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Attendance generated by hbm2java
 */
public class Attendance  implements java.io.Serializable {


     private String employeeId;
     private Date dateFrom;
     private String officeIn;
     private String officeOut;
     private String status;
     private String remarks;

    public Attendance() {
    }

	
    public Attendance(String employeeId, String officeIn, String officeOut) {
        this.employeeId = employeeId;
        this.officeIn = officeIn;
        this.officeOut = officeOut;
    }
    public Attendance(String employeeId, Date dateFrom, String officeIn, String officeOut, String status, String remarks) {
       this.employeeId = employeeId;
       this.dateFrom = dateFrom;
       this.officeIn = officeIn;
       this.officeOut = officeOut;
       this.status = status;
       this.remarks = remarks;
    }
   
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public Date getDateFrom() {
        return this.dateFrom;
    }
    
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }
    public String getOfficeIn() {
        return this.officeIn;
    }
    
    public void setOfficeIn(String officeIn) {
        this.officeIn = officeIn;
    }
    public String getOfficeOut() {
        return this.officeOut;
    }
    
    public void setOfficeOut(String officeOut) {
        this.officeOut = officeOut;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


