package dao;
// Generated Dec 18, 2014 9:57:35 AM by Hibernate Tools 3.6.0



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String userId;
     private String password;
     private String employeeType;
     private String department;
     private String unit;
     private String lastLoginOn;
     private String firstName;
     private String lastName;
     private String userName;
     private String email;

    public Admin() {
    }

	
    public Admin(String userId) {
        this.userId = userId;
    }
    public Admin(String userId, String password, String employeeType, String department, String unit, String lastLoginOn, String firstName, String lastName, String userName, String email) {
       this.userId = userId;
       this.password = password;
       this.employeeType = employeeType;
       this.department = department;
       this.unit = unit;
       this.lastLoginOn = lastLoginOn;
       this.firstName = firstName;
       this.lastName = lastName;
       this.userName = userName;
       this.email = email;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmployeeType() {
        return this.employeeType;
    }
    
    public void setEmployeeType(String employeeType) {
        this.employeeType = employeeType;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getLastLoginOn() {
        return this.lastLoginOn;
    }
    
    public void setLastLoginOn(String lastLoginOn) {
        this.lastLoginOn = lastLoginOn;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


