package leave;
// Generated Dec 18, 2014 9:57:35 AM by Hibernate Tools 3.6.0



/**
 * LeaveForm generated by hbm2java
 */
public class LeaveForm  implements java.io.Serializable {


     private int dayCount;
     private String employeeId;
     private String employeeName;
     private String month;
     private String department;
     private String leaveType;

    public LeaveForm() {
    }

    public LeaveForm(String employeeId) {
        this.employeeId = employeeId;
    }
      

    public LeaveForm(int dayCount, String employeeId, String employeeName, String month, String department, String leaveType) {
       this.dayCount = dayCount;
       this.employeeId = employeeId;
       this.employeeName = employeeName;
       this.month = month;
       this.department = department;
       this.leaveType = leaveType;
    }
   
    public int getDayCount() {
        return this.dayCount;
    }
    
    public void setDayCount(int dayCount) {
        this.dayCount = dayCount;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public String getEmployeeName() {
        return this.employeeName;
    }
    
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getLeaveType() {
        return this.leaveType;
    }
    
    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType;
    }




}


