package leave;
// Generated Dec 18, 2014 9:57:35 AM by Hibernate Tools 3.6.0



/**
 * Leave generated by hbm2java
 */
public class Leave  implements java.io.Serializable {


     private int casualLeave;
     private Integer medicalLeave;
     private Integer specialLeave;
     private Integer officeLeave;
     private Integer leaveWithoutPay;
     private Integer leaveWithPay;
     private String employeeId;

    public Leave() {
    }

	
    public Leave(int casualLeave) {
        this.casualLeave = casualLeave;
    }
    public Leave(int casualLeave, Integer medicalLeave, Integer specialLeave, Integer officeLeave, Integer leaveWithoutPay, Integer leaveWithPay, String employeeId) {
       this.casualLeave = casualLeave;
       this.medicalLeave = medicalLeave;
       this.specialLeave = specialLeave;
       this.officeLeave = officeLeave;
       this.leaveWithoutPay = leaveWithoutPay;
       this.leaveWithPay = leaveWithPay;
       this.employeeId = employeeId;
    }
   
    public int getCasualLeave() {
        return this.casualLeave;
    }
    
    public void setCasualLeave(int casualLeave) {
        this.casualLeave = casualLeave;
    }
    public Integer getMedicalLeave() {
        return this.medicalLeave;
    }
    
    public void setMedicalLeave(Integer medicalLeave) {
        this.medicalLeave = medicalLeave;
    }
    public Integer getSpecialLeave() {
        return this.specialLeave;
    }
    
    public void setSpecialLeave(Integer specialLeave) {
        this.specialLeave = specialLeave;
    }
    public Integer getOfficeLeave() {
        return this.officeLeave;
    }
    
    public void setOfficeLeave(Integer officeLeave) {
        this.officeLeave = officeLeave;
    }
    public Integer getLeaveWithoutPay() {
        return this.leaveWithoutPay;
    }
    
    public void setLeaveWithoutPay(Integer leaveWithoutPay) {
        this.leaveWithoutPay = leaveWithoutPay;
    }
    public Integer getLeaveWithPay() {
        return this.leaveWithPay;
    }
    
    public void setLeaveWithPay(Integer leaveWithPay) {
        this.leaveWithPay = leaveWithPay;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }




}


